Update nightly.yml

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -1,21 +1,27 @@
 name: Nightly Build of Aurora Editor
-
 on:
   push:
-    branches:
-      - 'testing/github-action'
+     branches: [ development ]
 
 jobs:
   build_nightly_editor:
+    if: github.repository_owner == 'AuroraEditor'
     runs-on: macos-12
-    timeout-minutes: 30 # If a build exceeds 30 mins, it probably isn't ever going to complete
+    timeout-minutes: 30 # If a build exceeds 430 mins, it probably isn't ever going to complete
     steps:
+      - name: 'Cleanup build folder'
+        run: |
+          ls -la ./
+          rm -rf ./* || true
+          rm -rf ./.??* || true
+          ls -la ./
+        
       - uses: actions/checkout@v3
       
       - name: "Select Xcode 14.0"
         run: sudo xcode-select -s /Applications/Xcode_14.0.app
         
-      ### Certs
+        ### Certs
       - name: "Import Certificate: Development"
         env:
           BUILD_CERTIFICATE_BASE64: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
@@ -66,109 +72,47 @@ jobs:
           security list-keychain -d user -s $KEYCHAIN_PATH
 
       - name: "Update version number"
-        run: agvtool new-version -all `date -u "+%Y%m%d.%H%M"`
-
-      - name: "Create Release Build Archive"
-        run: | 
-          set -o pipefail && xcodebuild -workspace "Aurora Editor.xcworkspace" -scheme "Aurora Editor (Release)" -configuration Release archive -archivePath "builds/Aurora Editor.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty 
-
-      - name: "Export Release Build"
         run: |
-          xcrun xcodebuild -exportArchive -exportOptionsPlist .github/export.plist -archivePath "builds/Aurora Editor.xcarchive" -exportPath builds
-        
-      - name: Install create-dmg
-        run: npm install --global create-dmg
-        
-      - name: Make Release Dmg
-        run: create-dmg "builds/Aurora Editor.app"
-
-      - name: "notarytool submit"
-        run: xcrun notarytool submit "Aurora Editor 1.0.dmg" --apple-id "${{ secrets.APPLEID_EMAIL }}" --password "${{ secrets.APPLEID_PASSWORD }}" --team-id "4V2D72S45C" --wait
-        
-      # - name: "Staple Release Build"
-      # run: xcrun stapler staple "Aurora Editor 1.0.dmg"
-        
-      - name: Upload a Build Artifact
-        uses: actions/upload-artifact@v3.0.0
-        with:
-          # Artifact name
-          name: AuroraEditor_Nightly # optional, default is artifact
-          # A file, directory or wildcard pattern that describes what to upload
-          path: "Aurora Editor 1.0.dmg"
-        
-      - name: Clean up keychain and provisioning profile
-        if: ${{ always() }}
-        run: |
-          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
-
-      - name: Extract Version Info and Calculate SHA-256
-        id: version_and_sha
-        run: |
-          # Get the version name (CFBundleShortVersionString)
-          version_name=$(agvtool what-marketing-version -terse1)
-          # Get the version code (CFBundleVersion)
-          version_code=$(agvtool what-version -terse)
-          sha256sum=$(shasum -a 256 "Aurora Editor 1.0.dmg" | awk '{ print $1 }')
+          # Calculate the new version number based on SemVer
+          current_version=$(agvtool what-marketing-version -terse1)
+          IFS='.' read -r -a version_parts <<< "$current_version"
     
-          echo "Version Name: $version_name"
-          echo "Version Code: $version_code"
-          echo "sha256sum: $sha256sum"
+          # Increment the version components based on commit messages
+          new_major=${version_parts[0]}
+          new_minor=${version_parts[1]}
+          new_patch=${version_parts[2]}
 
-          echo "version_name=$version_name" >> $GITHUB_OUTPUT
-          echo "version_code=$version_code" >> $GITHUB_OUTPUT
-          echo "sha256sum=$sha256sum" >> $GITHUB_OUTPUT
-
-      - name: Create a Updated nightly.json File
-        run: |
-          version_name=${{ steps.version_and_sha.outputs.version_name }}
-          version_code=${{ steps.version_and_sha.outputs.version_code }}
-          sha256sum=${{ steps.version_and_sha.outputs.sha256sum }}
-          
-          echo "{\"versionCode\": \"$version_code\", \"versionName\": \"$version_name\", \"sha256sum\": \"$sha256sum\", \"url\": \"https://nightly.link/AuroraEditor/AuroraEditor/workflows/nightly/main/AuroraEditor_Nightly.zip\"}" > app_info.json
-
-      - name: Get SHA of nightly.json file
-        id: get_sha
-        env:
-          PAT: ${{ secrets.BOT_TOKEN }}
-        run: |
-          result=$(curl -s -H "Authorization: Bearer $PAT" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/AuroraEditor/auroraeditor.com/contents/public/updates/dynamic/macos/nightly.json 2>&1)
+          echo "New version: $new_major.$new_minor.$new_patch"
     
-          # Check for errors and log stderr
-          if [ $? -ne 0 ]; then
-            echo "Error occurred during curl request:"
-            echo "$result"
-            exit 1
+          # Get the list of commit messages since the last version
+          commit_messages=$(git log --oneline $(git describe --tags --abbrev=0)..HEAD --format="%s")
+
+          version_name="V1.0.0"
+    
+          # Check commit messages for keywords
+          if echo "$commit_messages" | grep -q "breaking"; then
+            ((new_major++))
+            new_minor=0
+            new_patch=0
+            version_name="V$new_major"
+          elif echo "$commit_messages" | grep -q "feature"; then
+            ((new_minor++))
+            new_patch=0
+            version_name="V$new_major.$new_minor"
+          else
+            ((new_patch++))
+            version_name="V$new_major.$new_minor.$new_patch"
           fi
     
-          # Extract SHA from the JSON response
-          SHA=$(echo "$result" | jq -r '.sha')
-    
-          # Log the SHA and stderr
-          echo "SHA: $SHA"
-          echo "Curl Output:"
-          echo "$result"
+          # Generate the new version number
+          new_version="$new_major.$new_minor.$new_patch"
 
-          echo "sha=$SHA" >> $GITHUB_OUTPUT
-
-      - name: Commit Updated nightly.json to auroraeditor.com Repository
-        env:
-          PAT: ${{ secrets.BOT_TOKEN }}
-        run: |
-          sha=${{ steps.get_sha.outputs.sha }}
-          json_content=$(cat app_info.json)
-          commit_message="Updated nightly.json"
-    
-          # Define the API URL
-          api_url="https://api.github.com/repos/AuroraEditor/auroraeditor.com/contents/public/updates/dynamic/macos/nightly.json"
-
-          # Log the URL, path, and content being sent
-          echo "URL: $api_url"
-          echo "Content:"
-          echo "$json_content"
-
-          # Use curl to create the commit with the updated JSON file
-          curl -H "Authorization: Bearer $PAT" -X PUT \
-            -d "{\"message\": \"$commit_message\", \"content\": \"$(base64 <<< $json_content)\", \"branch\": \"main\", \"sha\": \"$sha\"}" \
-            "$api_url"
+          if [[ $new_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            agvtool new-marketing-version "$new_version"
+            echo "New version: $new_version"
+            echo "Version name: $version_name"
+           else
+            agvtool new-marketing-version "$current_version"
+            echo "Invalid new version, falling back to the old version: $current_version"
+            echo "Version name: $version_name"
+          fi
